# 后端服务器端口号配置 8090
server:
  port: 8090

# spring 项目配置
spring:
  application:
    name: rtms-backend
  datasource:
    url: jdbc:mysql://localhost:3306/db_rtms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 文件保存路径默认在服务器的下载文件夹中,在部署时需要按照下列路径创建好对应的文件夹
img:
  root: 'D:\code\rtms\rtms-back\img'

# slf4j 日志配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{15} ===> %msg%n"

# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.shihailiang.rtmsbackend.controller


knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content:
